// Generated by CoffeeScript 2.7.0
(function() {
  // src/contrastChecker.coffee
  var contrastRatio, hexToRgb, luminance;

  hexToRgb = function(hex) {
    var b, g, r;
    hex = hex.replace("#", "");
    r = parseInt(hex.substring(0, 2), 16);
    g = parseInt(hex.substring(2, 4), 16);
    b = parseInt(hex.substring(4, 6), 16);
    return [r, g, b];
  };

  luminance = function(rgb) {
    var b, g, r;
    [r, g, b] = rgb.map(function(value) {
      value /= 255.0;
      if (value <= 0.03928) {
        return value /= 12.92;
      } else {
        return ((value + 0.055) / 1.055) ** 2.4;
      }
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  };

  contrastRatio = function(color1, color2) {
    var lum1, lum2;
    lum1 = luminance(color1) + 0.05;
    lum2 = luminance(color2) + 0.05;
    if (lum1 > lum2) {
      return lum1 / lum2;
    } else {
      return lum2 / lum1;
    }
  };

  module.exports = {contrastRatio};

}).call(this);
