// Generated by CoffeeScript 2.7.0
(function() {
  // src/keyboardChecker.coffee
  var checkTabIndex;

  checkTabIndex = function(element) {
    if (element.tabIndex < 0) {
      console.warn("Inaccessible element:", element);
      return "Element is not accessible via keyboard.";
    }
  };

  module.exports = {checkTabIndex};

}).call(this);
